name: Marlin Build MKS TinyBee

on:
  workflow_dispatch: # Manuel başlatma butonu
  push:
    branches:
      - bugfix-2.1.x # Eğer branş ismin farklıysa (master veya main gibi) burayı değiştir
    paths:
      - '**/Configuration.h'
      - '**/Configuration_adv.h'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache Pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio
        restore-keys: |
          ${{ runner.os }}-platformio

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run Build for MKS TinyBee
      run: |
        # Bu komut platformio.ini içindeki mks_tinybee ortamını derler
        pio run -e mks_tinybee

    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: MKS_TinyBee_Firmware
        path: .pio/build/mks_tinybee/firmware.bin