name: Marlin Build MKS TinyBee

on:
  workflow_dispatch: # Manuel başlatma butonu (Kesinlikle olmalı)
  push:
    branches:
      - "*" # Tüm branşlarda çalışması için yıldız koyduk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run Build for MKS TinyBee
      run: |
        # Kütüphane hatalarını önlemek için önce bağımlılıkları yükle
        pio run -e mks_tinybee --target clean
        pio run -e mks_tinybee

    - name: Upload Firmware
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: MKS_TinyBee_Firmware
        path: .pio/build/mks_tinybee/firmware.bin
