name: Marlin Build MKS TinyBee

on:
  workflow_dispatch: # Manuel başlatma butonu sağlar
  push:
    branches:
      - bugfix-2.1.x # Kullandığın branş ismi master veya main ise burayı ona göre değiştir
    paths:
      - '**/Configuration.h'
      - '**/Configuration_adv.h'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run Build for MKS TinyBee
      run: |
        # TinyBee için derleme komutu
        pio run -e mks_tinybee

    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: MKS_TinyBee_Firmware
        path: .pio/build/mks_tinybee/firmware.bin
